### ISSUE TITLE
restclient does not compile with scala 2.10.x

### ISSUE THREAD

**Issue by mshirman** [nraychaudhuri/scalainaction#2]
Hello Nilanjan,
I'm enjoying your book. As I'm going through the samples I test them. Chapter 2's rest client would not compile with scala 2.10. Here are the compilation errors i get (it is fine with 2.9.1): 

...Temp\sbt_87024add\API.scala:263: error: type mismatch;
 found   : String
 required: ?{def endsWith(x$1: ? >: API.this.global.tpnme.NameType): Boolean}
Note that implicit conversions are not applicable because they are ambiguous:
 both method stringToTermName in trait Names of type (s: String)API.this.global.TermName
 and method stringToTypeName in trait Names of type (s: String)API.this.global.TypeName
 are possible conversion functions from String to ?{def endsWith(x$1: ? >: API.this.global.tpnme.Nam
eType): Boolean}
                sym.isLocalClass || sym.isAnonymousClass || sym.fullName.endsWith(LocalChild)
                                                                ^
...\Temp\sbt_87024add\API.scala:263: error: type mismatch;
 found   : API.this.global.tpnme.NameType
    (which expands to)  API.this.global.TypeName
 required: String
                sym.isLocalClass || sym.isAnonymousClass || sym.fullName.endsWith(LocalChild)
                                                                                  ^
two errors found

**Comment by mshirman** [comment]
Quick update, one would need to use 0.12.3 sbt version with 2.10.x scala. Then in compiles fine...
